### ISSUE TITLE
Consumos [29/05]

### ISSUE THREAD

**Issue by eumati** [eumati/cemv#7]
- En base a las pestañas [Consumo de cementos, Consumo de agregados], hacer un formulario para captura de la infomracion:
 * Agregar: aparecera una tabla con tres columnas [agregado, cantidad, observaciones], los agregados que tengan [1] en el campo de "consumo" se cargaran automaticamente, ademas de que habra un typeahead para poder agregar nuevos agregados de cualquier tipo a la tabla, y un campo para capturar la fecha del registro
  * Agregara tantos registros como se muestran en la tabla
 * Modificar: solo se podra modificar la informacion de un solo registro, y solo los campos [cantidad, observaciones]
 * Eliminar: solo eliminara el registro seleccionado

**Comment by josuevidal** [comment]
cuando se guarda si se agregan los datos en la base de datos, pero en la tabla no aparecen
